import { serve } from "bun";
import { join } from "path";
import { readFileSync } from "fs";

const PORT = 3000;
// We target the dist folder generated by Vite in src/js
const DIST_DIR = join(import.meta.dir, "src/js/dist");

console.log(`Local D2 Playground running securely at http://localhost:${PORT}`);

serve({
  port: PORT,
  fetch(req) {
    const url = new URL(req.url);
    let path = url.pathname === "/" ? "/index.html" : url.pathname;
    
    try {
      const file = readFileSync(join(DIST_DIR, path));
      let contentType = "text/html";
      if (path.endsWith(".js")) contentType = "application/javascript";
      if (path.endsWith(".css")) contentType = "text/css";
      if (path.endsWith(".wasm")) contentType = "application/wasm";
      if (path.endsWith(".svg")) contentType = "image/svg+xml";

      return new Response(file, { headers: { "Content-Type": contentType } });
    } catch (e) {
      return new Response("404 Not Found", { status: 404 });
    }
  },
});
