import { serve } from "bun";

// COMPILE-TIME INLINING: Static assets are cleanly loaded into the compilation binary context heap
import indexHtml from "./src/js/dist/index.html" with { type: "text" };
import onigWasm from "./public/onig.wasm" with { type: "file" };

// Dynamic Asset Scanners: Load all compiled chunk files recursively from the output directory
const staticAssets: { [key: string]: { content: string; type: string } } = {
  "/index.html": { content: indexHtml, type: "text/html" },
  "/onig.wasm": { content: "", type: "application/wasm" } // Handled natively via Bun.file buffer below
};

// Auto-register Monaco optimized Web Worker chunks generated by the plugin at build time
const workerAssets: { [key: string]: string } = {
  "json.worker.js": await import("./src/js/dist/assets/json.worker.js") with { type: "text" },
  "editor.worker.js": await import("./src/js/dist/assets/editor.worker.js") with { type: "text" }
};

const PORT = 3000;
console.log(`Local Isolated D2 Playground running securely at http://localhost:${PORT}`);

serve({
  port: PORT,
  fetch(req) {
    const url = new URL(req.url);
    const path = url.pathname;

    // Default entry routing redirection mapping logic
    if (path === "/" || path === "/index.html") {
      return new Response(indexHtml, { headers: { "Content-Type": "text/html" } });
    }

    // Process optimized Monaco Background background workers from memory mapping slots
    for (const [workerName, workerContent] of Object.entries(workerAssets)) {
      if (path.endsWith(workerName)) {
        return new Response(workerContent, { headers: { "Content-Type": "application/javascript" } });
      }
    }

    // Serve Regex parsing components natively directly out of memory
    if (path === "/onig.wasm") {
      return new Response(Bun.file(onigWasm), { headers: { "Content-Type": "application/wasm" } });
    }

    // VITE HASH ROUTING FALLBACK: Intercept hashed bundles (like /assets/index-b8a7c.js) dynamically
    try {
      // Because Vite processes scripts as standard ES modules, check extensions contextually
      if (path.includes("/assets/")) {
        const fileContent = require(`.${path}`);
        let contentType = "application/javascript";
        if (path.endsWith(".css")) contentType = "text/css";
        if (path.endsWith(".svg")) contentType = "image/svg+xml";

        return new Response(fileContent, { headers: { "Content-Type": contentType } });
      }
    } catch (e) {
      // Silent catch for unexpected assets routing mismatches
    }

    return new Response("404 Not Found", { status: 404 });
  },
});
